### ISSUE TITLE
Repeat

### ISSUE THREAD

**Issue by yuceltoluyag** [scanhand/EasyRecorder#3]
First of all, thanks for this program. Can you add the ability to repeat the operations the number of times entered?

**Comment by scanhand** [comment]
Ok, I will add a repeat configuration. Maybe this configuration will add after adding a configuration window.

**Comment by scanhand** [comment]
I have added a repeat count in v 0.0.3.0.
So, you can download a new version and can use a repeat control.

**Comment by yuceltoluyag** [comment]
thanks for your quick reply but this is countdown, For example let's automatically  repeat a recorded action as many times as we enter. @scanhand

**Comment by scanhand** [comment]
You can immediately stop by ESC key during playing.
